treadmill-ci-test: add report-success step, as in tock/tock

diff --git a/.github/workflows/treadmill-ci-test.yml b/.github/workflows/treadmill-ci-test.yml
--- a/.github/workflows/treadmill-ci-test.yml
+++ b/.github/workflows/treadmill-ci-test.yml
@@ -17,6 +17,7 @@ on:
   merge_group:
     branches: [main]
     types: [checks_requested]
+
   # Pull requests from forks will not have access to the required GitHub API
   # secrets below, even if they are using an appropriate deployment environment
   # and the workflow runs have been approved according to this environment's
@@ -26,6 +27,7 @@ on:
   # and starting Treadmill jobs with those runner registration tokens), which
   # allows this workflow to run without access to repository secrets.
   #pull_request:
+
   workflow_dispatch:
     inputs:
       tock-kernel-ref:
@@ -37,18 +39,18 @@ on:
         required: true
         default: 'master'
       tests-json:
-        description: 'tests-json value passed to HWCI workflow (if empty, output from analyze-changes step is used)'
+        description: 'tests-json value passed to HWCI workflow (if empty, output from hwci-determine-tests step is used)'
         required: false
 
 permissions:
   contents: read
 
 jobs:
-  analyze-changes:
+  hwci-determine-tests:
     runs-on: ubuntu-latest
 
     outputs:
-      hwci-tests-json: ${{ steps.analyze-changes.outputs.hwci-tests-json }}
+      hwci-tests-json: ${{ steps.determine-tests.outputs.hwci-tests-json }}
 
     steps:
       # This is not run within the context of a repository that contains actual
@@ -67,7 +69,7 @@ jobs:
           path: tock-tock
 
       - name: Select all defined tests
-        id: analyze-changes
+        id: determine-tests
         run: |
           # Run the select_tests.py script
           python3 tock-hardware-ci/hwci/select_tests.py \
@@ -82,14 +84,14 @@ jobs:
           hwci_tests_json=$(cat selected_tests.json | jq -c '.')
           echo "hwci-tests-json=${hwci_tests_json}" >> "$GITHUB_OUTPUT"
 
-  run-treadmill-ci:
-    needs: [analyze-changes]
+  hwci-treadmill-dispatch:
+    needs: [hwci-determine-tests]
 
     uses: ./.github/workflows/treadmill-ci.yml
 
     # This checks whether there is at least one test to run, see
     # https://github.com/orgs/community/discussions/27125#discussioncomment-3254720
-    if: fromJSON(needs.analyze-changes.outputs.hwci-tests-json)[0] != null
+    if: fromJSON(needs.hwci-determine-tests.outputs.hwci-tests-json)[0] != null
 
     with:
       # Only run on a specific repository, as others will not have the right
@@ -109,6 +111,25 @@ jobs:
       # Use the latest upstream Tock kernel / userspace components:
       tock-kernel-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.tock-kernel-ref || 'master' }}
       libtock-c-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.libtock-c-ref || 'master' }}
-      tests-json: ${{ (github.event_name == 'workflow_dispatch' && inputs.tests-json != '') && inputs.tests-json || needs.analyze-changes.outputs.hwci-tests-json }}
+      tests-json: ${{ (github.event_name == 'workflow_dispatch' && inputs.tests-json != '') && inputs.tests-json || needs.hwci-determine-tests.outputs.hwci-tests-json }}
 
     secrets: inherit
+
+  # We cannot depend on *all* test-execute jobs of hwci-treadmill-dispatch as
+  # required checks for pull requests and merge queues. Thus, we run another
+  # single dummy step here that waits for all the hwci-treadmill-dispatch jobs
+  # to complete and report success.
+  #
+  # We also use this to report a "dummy" success value for the "pull_request"
+  # trigger, as explained in the comment of the "on:" parameters above.
+  hwci-report-success:
+    needs: [hwci-determine-tests, hwci-treadmill-dispatch]
+
+    if: always()
+
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Fail if any of the 'hwci-treadmill-dispatch' jobs failed
+        if: github.event_name != 'pull_request' && contains(needs.*.result, 'failure')
+        run: exit 1
